create table customer
(
    id                     INT GENERATED ALWAYS AS IDENTITY,
    full_name              VARCHAR(100) NOT NULL,
    birthday              DATE         NOT NULL,
    passport_id            VARCHAR(30)  NOT NULL,
    address                VARCHAR(100) NOT NULL,
    phone                  VARCHAR(50)  NOT NULL,
    sms_phone              VARCHAR(50)  NOT NULL,
    fine_enabled           SMALLINT default 0,
    black_list             SMALLINT default 0,
    comment                VARCHAR(200),
    note                   VARCHAR(200),
    weeks_note             VARCHAR(200),
    taxi_company           VARCHAR(50),
    bort_number            VARCHAR(50),
    shift                  VARCHAR(50),
    place_of_birth         VARCHAR(100),
    marital_status         VARCHAR(30),
    partner_full_name      VARCHAR(50),
    partner_workplace      VARCHAR(50),
    partner_phone          VARCHAR(50),
    brother_phone          VARCHAR(50),
    sister_phone           VARCHAR(50),
    mother_phone           VARCHAR(50),
    father_phone           VARCHAR(50),
    roommate_phone         VARCHAR(50),
    mother_full_name       VARCHAR(50),
    father_full_name       VARCHAR(50),
    sister_full_name       VARCHAR(50),
    brother_full_name      VARCHAR(50),
    parent_work_place      VARCHAR(100),
    work_place             VARCHAR(100),
    work_place_more        VARCHAR(200),
    number_of_children     INT          NOT NULL,
    actual_address         VARCHAR(100),
    relatives_phones       VARCHAR(100),
    days_salary_level      INT          NOT NULL,
    other_income           VARCHAR(100),
    monthly_payments       VARCHAR(100),
    ownership              VARCHAR(200),
    received_credit_before   VARCHAR(100),
    date_of_questioning    DATE,
    affiliate_id           INT          NOT NULL,
    balance                INT default 0,
    employee_create_id     INT          NOT NULL,
    employee_update_id     INT,
    is_arrested            SMALLINT default 0,
    arrested_date          VARCHAR(50),
    color                  VARCHAR(10),
    regular_comment        VARCHAR(200),
    disable_fine_till_date DATE,

    PRIMARY KEY (id),
    CONSTRAINT customer_id UNIQUE (id),
    CONSTRAINT fk_affiliates_customer
        FOREIGN KEY (affiliate_id)
            REFERENCES affiliates (id)
);

create index customer_id_index
    on customer (id)
